### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [eegbunam/twitterApi#1]
It looks like we can’t locate the video walkthrough for this submission. Can you add it to your repository?

**Comment by eegbunam** [comment]
Done!

**Comment by codepathreview** [comment]
We still can’t locate the video walkthrough for this submission. Can you add it again to your repository? 
/cc @codepathreview
